export type RelationshipResource='contacts'|'companies'|'projects'|'deals'|'conversations'|'team'|'products';
export type Field={key:string;label:string;type?:'text'|'email'|'tel'|'url'|'date'|'textarea'|'number'|'money'|'tags'|'checkbox'|'select'|'json';required?:boolean;options?:string[];help?:string;relationship?:RelationshipResource};
export type Option={value:string;label:string};
export type Stage={key:string;label:string;probability:number;outcome:'open'|'won'|'lost';expected_duration_hours?:number};
export type PipelineRecord={id:string;version:number;name:string;description?:string;status:string;is_default:boolean;stages:Stage[];loss_reasons?:string[]};
export type Resource={key:string;route:string;title:string;singular:string;gender?:'m'|'f';description:string;icon:string;fields:Field[];columns:string[];view?:'board'|'cards'|'tasks'|'knowledge'|'agents'|'automations'|'approvals'|'finance'};
// Portuguese agrees in gender, so the article travels with the resource instead of being concatenated blindly.
export const newLabel=(r:Resource)=>`${r.gender==='f'?'Nova':'Novo'} ${r.singular}`;
export const thisLabel=(r:Resource)=>`${r.gender==='f'?'esta':'este'} ${r.singular}`;
export const plural=(n:number,one:string,many:string)=>`${n} ${n===1?one:many}`;
const relationships:Record<string,RelationshipResource>={contact_id:'contacts',company_id:'companies',project_id:'projects',deal_id:'deals',conversation_id:'conversations',owner_id:'team'};
const field=(key:string,label:string,type:Field['type']='text',options?:string[]):Field=>({key,label,type,options,relationship:relationships[key]});
export const emptyStage=():Stage=>({key:'',label:'',probability:0,outcome:'open',expected_duration_hours:72});
export const stageKey=(label:string)=>label.normalize('NFD').replace(/[^\u0020-\u007e]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').replace(/^(?![a-z])/,'e').slice(0,40);
export const outcomes:Option[]=[{value:'open',label:'Em andamento'},{value:'won',label:'Ganho'},{value:'lost',label:'Perdido'}];
export const labels:Record<string,string>={lead:'Entrada',qualified:'Qualificação',proposal:'Proposta',negotiation:'Negociação',won:'Ganho',lost:'Perdido',new:'Novo',active:'Ativo',inactive:'Inativo',customer:'Cliente',qualified_contact:'Qualificado',todo:'A fazer',in_progress:'Em andamento',done:'Concluído',low:'Baixa',medium:'Média',high:'Alta',urgent:'Urgente',open:'Aberta',pending:'Pendente',closed:'Encerrada',draft:'Rascunho',scheduled:'Agendada',running:'Em execução',paused:'Pausado',completed:'Concluído',planning:'Planejamento',approved:'Aprovado',rejected:'Rejeitado',paid:'Pago',overdue:'Vencido',sent:'Enviado',internal:'Interno',whatsapp:'WhatsApp',instagram:'Instagram',email:'E-mail',available:'Disponível',not_configured:'Configuração pendente',manual:'Manual',service:'Serviço',general:'Geral',archived:'Arquivado',cancelled:'Cancelado',social:'Redes sociais',ads:'Anúncios',owner:'Proprietário',admin:'Administrador',member:'Integrante',viewer:'Leitura'};
const name=(label='Nome'):Field=>({key:'name',label,required:true});
const title=(label='Título'):Field=>({key:'title',label,required:true});
const status=(options:string[]):Field=>field('status','Status','select',options);
export const resources:Resource[]=[
 {key:'contacts',route:'contatos',title:'Contatos',singular:'contato',gender:'m',description:'Cada relacionamento, com todo o contexto.',icon:'Users',columns:['name','email','company','status','source'],fields:[name(),field('email','E-mail','email'),field('phone','Telefone','tel'),field('company','Empresa informada'),field('company_id','Empresa cadastrada'),field('owner_id','Responsável'),status(['new','qualified','customer','inactive']),field('source','Origem'),field('tags','Tags','tags'),field('score','Pontuação','number'),field('notes','Notas','textarea'),field('consent','Consentimento registrado','checkbox')]},
 {key:'companies',route:'empresas',title:'Empresas',singular:'empresa',gender:'f',description:'Uma visão organizada das empresas do seu ecossistema.',icon:'Building2',columns:['name','industry','email','status'],view:'cards',fields:[name(),field('industry','Segmento'),field('document','CNPJ / documento'),field('website','Site','url'),field('email','E-mail','email'),field('phone','Telefone','tel'),status(['active','inactive']),field('notes','Notas','textarea')]},
 {key:'deals',route:'pipeline',title:'Pipeline de vendas',singular:'oportunidade',gender:'f',description:'Transforme bons relacionamentos em próximos passos.',icon:'PanelsTopLeft',columns:['title','stage','value_cents'],view:'board',fields:[title('Nome da oportunidade'),field('value_cents','Valor da oportunidade (R$)','money'),field('pipeline_id','Funil','select'),field('stage','Etapa','select'),{...field('probability','Probabilidade (%)','number'),help:'Em branco assume a probabilidade configurada na etapa.'},{...field('lost_reason','Motivo da perda'),help:'Obrigatório para mover a oportunidade a uma etapa de perda.'},field('expected_close','Previsão de fechamento','date'),{...field('next_action_at','Próxima ação','date'),help:'Sem próxima ação marcada, a oportunidade aparece no Radar como pendente.'},field('contact_id','Contato'),field('company_id','Empresa cadastrada'),field('owner_id','Responsável'),field('notes','Notas','textarea')]},
 {key:'tasks',route:'tarefas',title:'Tarefas',singular:'tarefa',gender:'f',description:'Clareza sobre o que importa fazer agora.',icon:'CircleCheck',columns:['title','priority','due_date','status'],view:'tasks',fields:[title(),field('description','Descrição','textarea'),status(['todo','in_progress','done']),field('priority','Prioridade','select',['low','medium','high','urgent']),field('due_date','Prazo','date'),field('contact_id','Contato'),field('deal_id','Oportunidade'),field('project_id','Projeto'),field('owner_id','Responsável')]},
 {key:'projects',route:'projetos',title:'Projetos',singular:'projeto',gender:'m',description:'Da primeira ideia à entrega, acompanhe a evolução.',icon:'FolderKanban',columns:['name','status','progress','due_date'],view:'cards',fields:[name(),field('description','Descrição','textarea'),status(['planning','active','paused','completed']),field('progress','Progresso (%)','number'),field('budget_cents','Orçamento (R$)','money'),field('due_date','Previsão de entrega','date'),field('company_id','Empresa cadastrada'),field('owner_id','Responsável')]},
 {key:'campaigns',route:'campanhas',title:'Campanhas',singular:'campanha',gender:'f',description:'Organize mensagens, públicos e iniciativas de crescimento.',icon:'Megaphone',columns:['name','channel','status','budget_cents'],view:'cards',fields:[name(),field('channel','Canal','select',['email','whatsapp','instagram','social','ads']),status(['draft','paused','archived']),field('audience','Público'),field('budget_cents','Orçamento (R$)','money'),field('scheduled_at','Data prevista','date'),field('content','Conteúdo','textarea'),field('tags','Tags','tags')]},
 {key:'automations',route:'automacoes',title:'Automações',singular:'automação',gender:'f',description:'Desenhe jornadas. Valide os passos. Mantenha o controle.',icon:'Workflow',columns:['name','trigger','status'],view:'automations',fields:[name(),field('description','Descrição','textarea'),status(['draft','paused']),field('trigger','Gatilho','select',['manual','contact.created','deal.updated','message.received']),{...field('nodes','Nós do fluxo (JSON)','json'),help:'Lista de nós. A simulação não envia mensagens.'},{...field('edges','Conexões (JSON)','json'),help:'Lista de conexões entre os nós.'}]},
 {key:'agents',route:'ia',title:'Central de IA',singular:'agente',gender:'m',description:'Especialistas digitais, com objetivos e limites claros.',icon:'Sparkles',columns:['name','squad','role','autonomy'],view:'agents',fields:[name(),field('squad','Squad'),field('role','Especialidade'),field('description','Instruções e contexto','textarea'),status(['paused']),field('autonomy','Nível de autonomia','select',['A0','A1']),field('budget_cents','Limite de orçamento (R$)','money')]},
 {key:'knowledge',route:'conhecimento',title:'Base de conhecimento',singular:'documento',gender:'m',description:'O conhecimento da sua empresa, conectado e acessível.',icon:'BookOpen',columns:['title','category','source'],view:'knowledge',fields:[title(),field('category','Categoria'),field('content','Conteúdo','textarea'),field('source','Fonte'),field('tags','Tags','tags')]},
 {key:'invoices',route:'financeiro',title:'Financeiro',singular:'lançamento',gender:'m',description:'Organize valores, prazos e o acompanhamento financeiro.',icon:'Wallet',columns:['title','amount_cents','due_date','status'],view:'finance',fields:[title('Descrição'),field('amount_cents','Valor (R$)','money'),status(['draft','pending','paid','overdue','cancelled']),field('due_date','Vencimento','date'),field('company_id','Empresa cadastrada'),field('contact_id','Contato'),field('notes','Observações','textarea')]},
 {key:'products',route:'produtos',title:'Produtos e serviços',singular:'serviço',gender:'m',description:'Seu catálogo de ofertas em um único lugar.',icon:'Package',columns:['name','sku','price_cents','status'],view:'cards',fields:[name(),field('description','Descrição','textarea'),field('sku','Código / SKU'),field('price_cents','Preço (R$)','money'),field('category','Categoria'),status(['active','inactive'])]},
 {key:'approvals',route:'aprovacoes',title:'Aprovações',singular:'solicitação',gender:'f',description:'Decisões sensíveis passam pelas pessoas certas.',icon:'ShieldCheck',columns:['title','gate','status'],view:'approvals',fields:[title(),field('description','Contexto da decisão','textarea'),field('gate','Gate','select',['G1','G2','G3','G4','G5','G6']),field('intent','Intenção estruturada (JSON)','json')]},
];
export const conversationResource:Resource={key:'conversations',route:'conversas',title:'Conversas',singular:'conversa',gender:'f',description:'Todo o contexto. Uma conversa de cada vez.',icon:'MessagesSquare',columns:[],fields:[title('Assunto'),field('contact_id','Contato'),field('owner_id','Responsável'),field('channel','Canal','select',['internal','whatsapp','instagram','email']),status(['open','pending','closed'])]};
export const resourceByRoute=(route:string)=>resources.find(r=>r.route===route);
