import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {ArrowUpRight,Check,Layers3} from 'lucide-react';
import {PublicShell} from '@/components/public-shell';
import {LeadForm} from '@/components/lead-form';
import {landingPages} from '@/lib/content';
export function generateStaticParams(){return Object.keys(landingPages).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=landingPages[slug];return {title:p?.title,description:p?.lead,alternates:{canonical:`/lp/${slug}`}}}
export default async function Landing({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=landingPages[slug];if(!p)notFound();return <PublicShell><main id="main"><section className="site-container lp-hero"><div><span className="eyebrow">{p.kicker}</span><h1>{p.title}</h1><p className="page-lead">{p.lead}</p><a className="button-link mint" href="#diagnostico">{p.primaryCta} <ArrowUpRight size={18}/></a></div><aside className="lp-aside"><Layers3 size={48} strokeWidth={1}/><span className="eyebrow">{p.sideTag}</span><h2>{p.sideTitle}</h2><p>{p.sideBody}</p><ul>{p.sideBullets?.map(b=><li key={b}><Check size={17}/>{b}</li>)}</ul></aside></section><section className="site-container lp-section"><span className="eyebrow">O DESAFIO</span><h2>{p.problemTitle}</h2><p className="page-lead">{p.problemLead}</p><div className="three-grid">{p.pains?.map(a=><div className="plain-feature" key={a.title}><h3>{a.title}</h3><p>{a.body}</p></div>)}</div></section><section className="method-section"><div className="site-container lp-section"><span className="eyebrow">A SOLUÇÃO</span><h2>{p.solutionTitle}</h2><p className="page-lead">{p.solutionLead}</p><div className="three-grid">{p.modules?.map((a,i)=><div className="plain-feature" key={a.title}><span className="step-number">0{i+1}</span><h3>{a.title}</h3><p>{a.body}</p></div>)}</div></div></section><section className="site-container lp-section"><h2>{p.offerTitle}</h2><div className="offer-list">{p.offerItems?.map(o=><div key={o}><Check size={20}/>{o}</div>)}</div><div className="faq-list">{p.faq?.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</div></section><section className="contact-section" id="diagnostico"><div className="site-container contact-grid"><div><span className="eyebrow">VAMOS CONVERSAR</span><h2>Seu próximo passo<br/><em>começa aqui.</em></h2><p>Vamos desenhar uma solução para o seu cenário.</p></div><div className="contact-form-card"><h3>Conheça as possibilidades.</h3><LeadForm interest={p.title}/></div></div></section></main></PublicShell>}
