'use client';
import {useEffect,useState} from 'react';
import {Button,TextField,Label,Input,TextArea} from '@heroui/react';
import {ArrowUpRight,CheckCircle2,LoaderCircle} from 'lucide-react';
import {api} from '@/lib/api';
import Link from 'next/link';
export function LeadForm({interest='Diagnóstico estratégico'}:{interest?:string}){
 const [ready,setReady]=useState(false);useEffect(()=>setReady(true),[]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function submit(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();setError('');setBusy(true);const form=new FormData(event.currentTarget);const utm=new URLSearchParams(window.location.search);try{await api('/public/leads',{method:'POST',body:JSON.stringify({...Object.fromEntries(form),consent:form.get('consent')==='on',interest,...Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].map(k=>[k,utm.get(k)||'']))})});setDone(true)}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar. Tente novamente.')}finally{setBusy(false)}}
 if(done)return <div className="lead-success" role="status"><CheckCircle2 size={42}/><h3>Conversa iniciada.</h3><p>Recebemos seu contato. Nossa equipe vai conhecer seu momento e entrar em contato para o próximo passo.</p><Button variant="secondary" onPress={()=>setDone(false)}>Enviar outro contato</Button></div>;
 return <form method="post" className="lead-form" onSubmit={submit}><div className="form-row"><TextField name="name" isRequired><Label>Seu nome</Label><Input placeholder="Como podemos chamar você?" autoComplete="name"/></TextField><TextField name="company"><Label>Empresa</Label><Input placeholder="Nome do seu negócio" autoComplete="organization"/></TextField></div><div className="form-row"><TextField name="email" type="email" isRequired><Label>E-mail profissional</Label><Input placeholder="voce@empresa.com" autoComplete="email"/></TextField><TextField name="phone" type="tel"><Label>WhatsApp</Label><Input placeholder="(35) 99999-9999" autoComplete="tel"/></TextField></div><TextField name="message"><Label>O que você quer transformar?</Label><TextArea placeholder="Conte um pouco sobre o momento da sua empresa." rows={3}/></TextField><label className="consent"><input type="checkbox" name="consent" required/> <span>Concordo em receber contato da FAT Tech sobre esta solicitação e li a <Link href="/privacidade">Política de Privacidade</Link>.</span></label>{error&&<p className="error-alert" role="alert">{error}</p>}<Button type="submit" isDisabled={!ready||busy} className="fat-button full">{busy?<LoaderCircle className="spin" size={18}/>:<>Agendar meu diagnóstico <ArrowUpRight size={18}/></>}</Button><p className="form-footnote">Sem compromisso. Uma conversa sobre o seu próximo passo.</p></form>
}
