'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button,TextField,Label,TextArea} from '@heroui/react';
import {api,RecordData,PageData,textValue,money,dateLabel} from '@/lib/api';
import {Resource,labels} from '@/lib/resources';
import {useUser} from './auth-context';
import {PageHeader,Panel,RecordEditor,LoadState,EmptyState,StatusBadge} from './crm-ui';

type Section='activities'|'deals'|'tasks'|'conversations'|'history';
type Overview={record:RecordData}&Record<Section,PageData>;
const tabs:{key:'data'|Section;label:string}[]=[{key:'data',label:'Dados'},{key:'activities',label:'Notas e atividades'},{key:'deals',label:'Oportunidades'},{key:'tasks',label:'Tarefas'},{key:'conversations',label:'Conversas'},{key:'history',label:'Histórico'}];
export const recordHref=(kind:string,id:string)=>`/crm/${({contacts:'contatos',companies:'empresas',deals:'pipeline',tasks:'tarefas',conversations:'conversas'} as Record<string,string>)[kind]||kind}${['contacts','companies','deals'].includes(kind)?'/'+encodeURIComponent(id):'?abrir='+encodeURIComponent(id)}`;

export function RecordDetail({resource,id}:{resource:Resource;id:string}){
 const user=useUser();const [data,setData]=useState<Overview|null>(null),[tab,setTab]=useState<'data'|Section>('data'),[offset,setOffset]=useState(0),[tick,setTick]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');api<Overview>(`/records/${resource.key}/${id}/overview?limit=20&${tab}_offset=${offset}`,{signal:controller.signal}).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível abrir a ficha.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[id,resource.key,tab,offset,tick]);
 async function note(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');try{await api(`/records/${resource.key}/${id}/activities`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({type:f.get('type'),body:f.get('body')})});form.reset();setNotice('Atividade registrada.');setOffset(0);setTick(t=>t+1)}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.')}finally{setBusy(false)}}
 const record=data?.record;const section=data&&tab!=='data'?data[tab]:null;
 return <><Link className="text-button" href={'/crm/'+resource.route}>← Voltar para {resource.title.toLowerCase()}</Link><PageHeader title={textValue(record?.name||record?.title)||'Ficha do registro'} description="Dados, relacionamentos e histórico em um só lugar." action={record&&user?.permissions.write_records&&(resource.key==='deals'?<Link className="button-link secondary" href={'/crm/pipeline?abrir='+id}>Editar oportunidade</Link>:<Button variant="secondary" onPress={()=>setEditing(true)}>Editar dados</Button>)}/>
 <div className="record-tabs" role="tablist" aria-label="Seções da ficha">{tabs.map(t=><button key={t.key} role="tab" aria-selected={tab===t.key} onClick={()=>{setTab(t.key);setOffset(0)}}>{t.label}{data&&t.key!=='data'&&<small>{data[t.key].total}</small>}</button>)}</div>
 {notice&&<p className="success-alert" role="status">{notice}</p>}<LoadState loading={loading} error={error} reload={()=>setTick(t=>t+1)}/>
 {!loading&&data&&<Panel title={tabs.find(t=>t.key===tab)?.label||''}>
 {tab==='data'?<dl className="record-facts">{resource.fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.relationship&&record?.[f.key]?<Link href={recordHref(f.relationship,textValue(record[f.key]))}>{textValue(record[f.key.replace('_id','_name')])||'Abrir vínculo'}</Link>:f.type==='money'?money(record?.[f.key]):f.type==='checkbox'?(record?.[f.key]?'Sim':'Não'):labels[textValue(record?.[f.key])]||textValue(record?.[f.key])||'—'}</dd></div>)}</dl>:<>
 {tab==='activities'&&user?.permissions.write_records&&<form method="post" className="admin-form" onSubmit={note}><label className="select-field"><span>Tipo de atividade</span><select name="type"><option value="note">Nota</option><option value="call">Ligação</option><option value="meeting">Reunião</option></select></label><TextField name="body" isRequired><Label>Registro da atividade</Label><TextArea rows={3} maxLength={20000}/></TextField><Button className="fat-button" type="submit" isDisabled={busy}>Registrar atividade</Button></form>}
 {!section?.items.length?<EmptyState title="Nenhum registro nesta seção." description="Os próximos movimentos aparecerão aqui."/>:<ul className="record-timeline">{section.items.map(item=><li key={item.id}>{tab==='history'?<><strong>{textValue(item.label||item.action)}</strong><p>{textValue(item.resource_name)}</p><small>{textValue(item.actor_name)||'Sistema'} · {dateLabel(item.created_at)}</small></>:tab==='activities'?<><strong>{({note:'Nota',call:'Ligação',meeting:'Reunião'} as Record<string,string>)[textValue(item.type)]||'Atividade'}</strong><p className="preserve-lines">{textValue(item.body)}</p><small>{textValue(item.author_name)||'Equipe'} · {item.created_at?new Date(item.created_at).toLocaleString('pt-BR'):''}</small></>:<><Link href={recordHref(tab,item.id)}><strong>{textValue(item.title||item.name)||'Abrir registro'}</strong></Link><p>{item.value_cents!==undefined?money(item.value_cents):textValue(item.description||item.last_message)}</p><StatusBadge value={item.status||item.stage}/></>}</li>)}</ul>}
 {section&&section.total>20&&<div className="pagination"><span>{offset+1}–{Math.min(offset+20,section.total)} de {section.total}</span><Button variant="secondary" isDisabled={!offset} onPress={()=>setOffset(o=>Math.max(0,o-20))}>Anterior</Button><Button variant="secondary" isDisabled={offset+20>=section.total} onPress={()=>setOffset(o=>o+20)}>Próxima</Button></div>}</>}
 </Panel>}{editing&&record&&<RecordEditor resource={resource} record={record} onClose={()=>setEditing(false)} onSaved={()=>setTick(t=>t+1)}/>}</>;
}
